### ISSUE TITLE
重构目录

### ISSUE THREAD

**Issue by StudyingFather** [SFOI-Team/luogu-problem-list#6]
按难度划分目录虽然方便了新手，但似乎割裂了同一专题间不同内容的联系。

所以接下来还是按专题大类（搜索，DP，数学...）来划分目录，并将目录内内容按从易到难的顺序排列。

有建议的话欢迎讨论QAQ

**Comment by abc1763613206** [comment]
个人有点建议：     
建议新手同时按对应的组别订阅，比如说普及组题单，提高组题单，省选题单等等。     
那样可以考虑和那两位神仙的超级任务计划整合，比如说用Travis定期release，然后导出一个固定地址（可以用jsdelivr实现，套latest标签就行），使用者在超级任务计划里加一个"订阅"的功能就行。     
也可以考虑md文件固定格式，那样就可以写一个自动生成todo.list的轮子了

**Comment by StudyingFather** [comment]
> 个人有点建议：
> 建议新手同时按对应的组别订阅，比如说普及组题单，提高组题单，省选题单等等。
> 那样可以考虑和那两位神仙的超级任务计划整合，比如说用Travis定期release，然后导出一个固定地址（可以用jsdelivr实现，套latest标签就行），使用者在超级任务计划里加一个"订阅"的功能就行。
> 也可以考虑md文件固定格式，那样就可以写一个自动生成todo.list的轮子了

好主意，以后应该会考虑规范一下格式的。~~（可惜自己是个开发小白QwQ）~~

**Comment by bear-good** [comment]
可以考虑再导出另一种版本?

**Comment by StudyingFather** [comment]
> 可以考虑再导出另一种版本?

目前正在跟进其他 todolist 工具的开发情况，以后应该会导出适合其他 todolist 工具使用的版本。

**Comment by bear-good** [comment]
我是说可以**再制作一套按难度排序**的MD与pdf？

**Comment by StudyingFather** [comment]
> 我是说可以**再制作一套按难度排序**的MD与pdf？

现在各专题下面题目已经是按难度排序过的。
